[package]
name = "thumbpick"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "lightweight, scriptable, keyboard-centric image picker"
repository = "https://github.com/soliprem/thumbpick"
homepage = "https://github.com/soliprem/thumbpick"
readme = "README.md"
categories = ["multimedia::images"]
keywords = ["thumbnail", "images"]

[dependencies]
gtk4 = "0.10"
gdk-pixbuf = "0.21.5"
async-channel = "2.5.0"
walkdir = "2.5.0"
glib = "0.21.5"
rayon = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.4", features = ["derive", "env"] }
figment = { version = "0.10", features = ["toml", "env"] }
directories = "6.0"
